#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LenceryDB")]
	public partial class connectDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttblCategoria(tblCategoria instance);
    partial void UpdatetblCategoria(tblCategoria instance);
    partial void DeletetblCategoria(tblCategoria instance);
    partial void InserttblVenta(tblVenta instance);
    partial void UpdatetblVenta(tblVenta instance);
    partial void DeletetblVenta(tblVenta instance);
    partial void InserttblCliente(tblCliente instance);
    partial void UpdatetblCliente(tblCliente instance);
    partial void DeletetblCliente(tblCliente instance);
    partial void InserttblCompra(tblCompra instance);
    partial void UpdatetblCompra(tblCompra instance);
    partial void DeletetblCompra(tblCompra instance);
    partial void InserttblProducto(tblProducto instance);
    partial void UpdatetblProducto(tblProducto instance);
    partial void DeletetblProducto(tblProducto instance);
    partial void InserttblProveedor(tblProveedor instance);
    partial void UpdatetblProveedor(tblProveedor instance);
    partial void DeletetblProveedor(tblProveedor instance);
    partial void InserttblTipoUs(tblTipoUs instance);
    partial void UpdatetblTipoUs(tblTipoUs instance);
    partial void DeletetblTipoUs(tblTipoUs instance);
    partial void InserttblUsuario(tblUsuario instance);
    partial void UpdatetblUsuario(tblUsuario instance);
    partial void DeletetblUsuario(tblUsuario instance);
    #endregion
		
		public connectDBDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.LenceryDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public connectDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public connectDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public connectDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public connectDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblCategoria> tblCategoria
		{
			get
			{
				return this.GetTable<tblCategoria>();
			}
		}
		
		public System.Data.Linq.Table<tblVenta> tblVenta
		{
			get
			{
				return this.GetTable<tblVenta>();
			}
		}
		
		public System.Data.Linq.Table<tblCliente> tblCliente
		{
			get
			{
				return this.GetTable<tblCliente>();
			}
		}
		
		public System.Data.Linq.Table<tblCompra> tblCompra
		{
			get
			{
				return this.GetTable<tblCompra>();
			}
		}
		
		public System.Data.Linq.Table<tblProducto> tblProducto
		{
			get
			{
				return this.GetTable<tblProducto>();
			}
		}
		
		public System.Data.Linq.Table<tblProveedor> tblProveedor
		{
			get
			{
				return this.GetTable<tblProveedor>();
			}
		}
		
		public System.Data.Linq.Table<tblTipoUs> tblTipoUs
		{
			get
			{
				return this.GetTable<tblTipoUs>();
			}
		}
		
		public System.Data.Linq.Table<tblUsuario> tblUsuario
		{
			get
			{
				return this.GetTable<tblUsuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCategoria")]
	public partial class tblCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _catId;
		
		private string _catNombreCategoria;
		
		private System.Nullable<char> _catEstado;
		
		private EntitySet<tblProducto> _tblProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncatIdChanging(int value);
    partial void OncatIdChanged();
    partial void OncatNombreCategoriaChanging(string value);
    partial void OncatNombreCategoriaChanged();
    partial void OncatEstadoChanging(System.Nullable<char> value);
    partial void OncatEstadoChanged();
    #endregion
		
		public tblCategoria()
		{
			this._tblProducto = new EntitySet<tblProducto>(new Action<tblProducto>(this.attach_tblProducto), new Action<tblProducto>(this.detach_tblProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int catId
		{
			get
			{
				return this._catId;
			}
			set
			{
				if ((this._catId != value))
				{
					this.OncatIdChanging(value);
					this.SendPropertyChanging();
					this._catId = value;
					this.SendPropertyChanged("catId");
					this.OncatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catNombreCategoria", DbType="VarChar(50)")]
		public string catNombreCategoria
		{
			get
			{
				return this._catNombreCategoria;
			}
			set
			{
				if ((this._catNombreCategoria != value))
				{
					this.OncatNombreCategoriaChanging(value);
					this.SendPropertyChanging();
					this._catNombreCategoria = value;
					this.SendPropertyChanged("catNombreCategoria");
					this.OncatNombreCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catEstado", DbType="Char(1)")]
		public System.Nullable<char> catEstado
		{
			get
			{
				return this._catEstado;
			}
			set
			{
				if ((this._catEstado != value))
				{
					this.OncatEstadoChanging(value);
					this.SendPropertyChanging();
					this._catEstado = value;
					this.SendPropertyChanged("catEstado");
					this.OncatEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCategoria_tblProducto", Storage="_tblProducto", ThisKey="catId", OtherKey="catId")]
		public EntitySet<tblProducto> tblProducto
		{
			get
			{
				return this._tblProducto;
			}
			set
			{
				this._tblProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblProducto(tblProducto entity)
		{
			this.SendPropertyChanging();
			entity.tblCategoria = this;
		}
		
		private void detach_tblProducto(tblProducto entity)
		{
			this.SendPropertyChanging();
			entity.tblCategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVenta")]
	public partial class tblVenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _venId;
		
		private System.Nullable<System.DateTime> _venFechaVen;
		
		private System.Nullable<int> _venCantidad;
		
		private System.Nullable<double> _venCapital;
		
		private System.Nullable<int> _cliId;
		
		private System.Nullable<int> _proId;
		
		private EntityRef<tblCliente> _tblCliente;
		
		private EntityRef<tblProducto> _tblProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnvenIdChanging(int value);
    partial void OnvenIdChanged();
    partial void OnvenFechaVenChanging(System.Nullable<System.DateTime> value);
    partial void OnvenFechaVenChanged();
    partial void OnvenCantidadChanging(System.Nullable<int> value);
    partial void OnvenCantidadChanged();
    partial void OnvenCapitalChanging(System.Nullable<double> value);
    partial void OnvenCapitalChanged();
    partial void OncliIdChanging(System.Nullable<int> value);
    partial void OncliIdChanged();
    partial void OnproIdChanging(System.Nullable<int> value);
    partial void OnproIdChanged();
    #endregion
		
		public tblVenta()
		{
			this._tblCliente = default(EntityRef<tblCliente>);
			this._tblProducto = default(EntityRef<tblProducto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int venId
		{
			get
			{
				return this._venId;
			}
			set
			{
				if ((this._venId != value))
				{
					this.OnvenIdChanging(value);
					this.SendPropertyChanging();
					this._venId = value;
					this.SendPropertyChanged("venId");
					this.OnvenIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venFechaVen", DbType="DateTime")]
		public System.Nullable<System.DateTime> venFechaVen
		{
			get
			{
				return this._venFechaVen;
			}
			set
			{
				if ((this._venFechaVen != value))
				{
					this.OnvenFechaVenChanging(value);
					this.SendPropertyChanging();
					this._venFechaVen = value;
					this.SendPropertyChanged("venFechaVen");
					this.OnvenFechaVenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venCantidad", DbType="Int")]
		public System.Nullable<int> venCantidad
		{
			get
			{
				return this._venCantidad;
			}
			set
			{
				if ((this._venCantidad != value))
				{
					this.OnvenCantidadChanging(value);
					this.SendPropertyChanging();
					this._venCantidad = value;
					this.SendPropertyChanged("venCantidad");
					this.OnvenCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venCapital", DbType="Float")]
		public System.Nullable<double> venCapital
		{
			get
			{
				return this._venCapital;
			}
			set
			{
				if ((this._venCapital != value))
				{
					this.OnvenCapitalChanging(value);
					this.SendPropertyChanging();
					this._venCapital = value;
					this.SendPropertyChanged("venCapital");
					this.OnvenCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliId", DbType="Int")]
		public System.Nullable<int> cliId
		{
			get
			{
				return this._cliId;
			}
			set
			{
				if ((this._cliId != value))
				{
					if (this._tblCliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncliIdChanging(value);
					this.SendPropertyChanging();
					this._cliId = value;
					this.SendPropertyChanged("cliId");
					this.OncliIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proId", DbType="Int")]
		public System.Nullable<int> proId
		{
			get
			{
				return this._proId;
			}
			set
			{
				if ((this._proId != value))
				{
					if (this._tblProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproIdChanging(value);
					this.SendPropertyChanging();
					this._proId = value;
					this.SendPropertyChanged("proId");
					this.OnproIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCliente_tblVenta", Storage="_tblCliente", ThisKey="cliId", OtherKey="cliId", IsForeignKey=true)]
		public tblCliente tblCliente
		{
			get
			{
				return this._tblCliente.Entity;
			}
			set
			{
				tblCliente previousValue = this._tblCliente.Entity;
				if (((previousValue != value) 
							|| (this._tblCliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCliente.Entity = null;
						previousValue.tblVenta.Remove(this);
					}
					this._tblCliente.Entity = value;
					if ((value != null))
					{
						value.tblVenta.Add(this);
						this._cliId = value.cliId;
					}
					else
					{
						this._cliId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblCliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProducto_tblVenta", Storage="_tblProducto", ThisKey="proId", OtherKey="proId", IsForeignKey=true)]
		public tblProducto tblProducto
		{
			get
			{
				return this._tblProducto.Entity;
			}
			set
			{
				tblProducto previousValue = this._tblProducto.Entity;
				if (((previousValue != value) 
							|| (this._tblProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblProducto.Entity = null;
						previousValue.tblVenta.Remove(this);
					}
					this._tblProducto.Entity = value;
					if ((value != null))
					{
						value.tblVenta.Add(this);
						this._proId = value.proId;
					}
					else
					{
						this._proId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblProducto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCliente")]
	public partial class tblCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cliId;
		
		private string _cliNombre;
		
		private string _cliApellido;
		
		private string _cliCorreo;
		
		private string _cliLog;
		
		private string _cliClave;
		
		private string _cliDireccion;
		
		private string _cliTelf;
		
		private string _cliCi;
		
		private string _cliGenero;
		
		private System.Nullable<char> _cliEstado;
		
		private EntitySet<tblVenta> _tblVenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncliIdChanging(int value);
    partial void OncliIdChanged();
    partial void OncliNombreChanging(string value);
    partial void OncliNombreChanged();
    partial void OncliApellidoChanging(string value);
    partial void OncliApellidoChanged();
    partial void OncliCorreoChanging(string value);
    partial void OncliCorreoChanged();
    partial void OncliLogChanging(string value);
    partial void OncliLogChanged();
    partial void OncliClaveChanging(string value);
    partial void OncliClaveChanged();
    partial void OncliDireccionChanging(string value);
    partial void OncliDireccionChanged();
    partial void OncliTelfChanging(string value);
    partial void OncliTelfChanged();
    partial void OncliCiChanging(string value);
    partial void OncliCiChanged();
    partial void OncliGeneroChanging(string value);
    partial void OncliGeneroChanged();
    partial void OncliEstadoChanging(System.Nullable<char> value);
    partial void OncliEstadoChanged();
    #endregion
		
		public tblCliente()
		{
			this._tblVenta = new EntitySet<tblVenta>(new Action<tblVenta>(this.attach_tblVenta), new Action<tblVenta>(this.detach_tblVenta));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cliId
		{
			get
			{
				return this._cliId;
			}
			set
			{
				if ((this._cliId != value))
				{
					this.OncliIdChanging(value);
					this.SendPropertyChanging();
					this._cliId = value;
					this.SendPropertyChanged("cliId");
					this.OncliIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliNombre", DbType="VarChar(50)")]
		public string cliNombre
		{
			get
			{
				return this._cliNombre;
			}
			set
			{
				if ((this._cliNombre != value))
				{
					this.OncliNombreChanging(value);
					this.SendPropertyChanging();
					this._cliNombre = value;
					this.SendPropertyChanged("cliNombre");
					this.OncliNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliApellido", DbType="VarChar(50)")]
		public string cliApellido
		{
			get
			{
				return this._cliApellido;
			}
			set
			{
				if ((this._cliApellido != value))
				{
					this.OncliApellidoChanging(value);
					this.SendPropertyChanging();
					this._cliApellido = value;
					this.SendPropertyChanged("cliApellido");
					this.OncliApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliCorreo", DbType="VarChar(75)")]
		public string cliCorreo
		{
			get
			{
				return this._cliCorreo;
			}
			set
			{
				if ((this._cliCorreo != value))
				{
					this.OncliCorreoChanging(value);
					this.SendPropertyChanging();
					this._cliCorreo = value;
					this.SendPropertyChanged("cliCorreo");
					this.OncliCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliLog", DbType="VarChar(80)")]
		public string cliLog
		{
			get
			{
				return this._cliLog;
			}
			set
			{
				if ((this._cliLog != value))
				{
					this.OncliLogChanging(value);
					this.SendPropertyChanging();
					this._cliLog = value;
					this.SendPropertyChanged("cliLog");
					this.OncliLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliClave", DbType="VarChar(50)")]
		public string cliClave
		{
			get
			{
				return this._cliClave;
			}
			set
			{
				if ((this._cliClave != value))
				{
					this.OncliClaveChanging(value);
					this.SendPropertyChanging();
					this._cliClave = value;
					this.SendPropertyChanged("cliClave");
					this.OncliClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliDireccion", DbType="VarChar(75)")]
		public string cliDireccion
		{
			get
			{
				return this._cliDireccion;
			}
			set
			{
				if ((this._cliDireccion != value))
				{
					this.OncliDireccionChanging(value);
					this.SendPropertyChanging();
					this._cliDireccion = value;
					this.SendPropertyChanged("cliDireccion");
					this.OncliDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliTelf", DbType="VarChar(50)")]
		public string cliTelf
		{
			get
			{
				return this._cliTelf;
			}
			set
			{
				if ((this._cliTelf != value))
				{
					this.OncliTelfChanging(value);
					this.SendPropertyChanging();
					this._cliTelf = value;
					this.SendPropertyChanged("cliTelf");
					this.OncliTelfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliCi", DbType="VarChar(50)")]
		public string cliCi
		{
			get
			{
				return this._cliCi;
			}
			set
			{
				if ((this._cliCi != value))
				{
					this.OncliCiChanging(value);
					this.SendPropertyChanging();
					this._cliCi = value;
					this.SendPropertyChanged("cliCi");
					this.OncliCiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliGenero", DbType="VarChar(10)")]
		public string cliGenero
		{
			get
			{
				return this._cliGenero;
			}
			set
			{
				if ((this._cliGenero != value))
				{
					this.OncliGeneroChanging(value);
					this.SendPropertyChanging();
					this._cliGenero = value;
					this.SendPropertyChanged("cliGenero");
					this.OncliGeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliEstado", DbType="Char(1)")]
		public System.Nullable<char> cliEstado
		{
			get
			{
				return this._cliEstado;
			}
			set
			{
				if ((this._cliEstado != value))
				{
					this.OncliEstadoChanging(value);
					this.SendPropertyChanging();
					this._cliEstado = value;
					this.SendPropertyChanged("cliEstado");
					this.OncliEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCliente_tblVenta", Storage="_tblVenta", ThisKey="cliId", OtherKey="cliId")]
		public EntitySet<tblVenta> tblVenta
		{
			get
			{
				return this._tblVenta;
			}
			set
			{
				this._tblVenta.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblVenta(tblVenta entity)
		{
			this.SendPropertyChanging();
			entity.tblCliente = this;
		}
		
		private void detach_tblVenta(tblVenta entity)
		{
			this.SendPropertyChanging();
			entity.tblCliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCompra")]
	public partial class tblCompra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _comId;
		
		private string _comCodigo;
		
		private System.Nullable<System.DateTime> _comFechaCompra;
		
		private System.Nullable<int> _comCantidad;
		
		private System.Nullable<double> _comCapital;
		
		private System.Nullable<int> _provId;
		
		private System.Nullable<int> _proId;
		
		private EntityRef<tblProducto> _tblProducto;
		
		private EntityRef<tblProveedor> _tblProveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncomIdChanging(int value);
    partial void OncomIdChanged();
    partial void OncomCodigoChanging(string value);
    partial void OncomCodigoChanged();
    partial void OncomFechaCompraChanging(System.Nullable<System.DateTime> value);
    partial void OncomFechaCompraChanged();
    partial void OncomCantidadChanging(System.Nullable<int> value);
    partial void OncomCantidadChanged();
    partial void OncomCapitalChanging(System.Nullable<double> value);
    partial void OncomCapitalChanged();
    partial void OnprovIdChanging(System.Nullable<int> value);
    partial void OnprovIdChanged();
    partial void OnproIdChanging(System.Nullable<int> value);
    partial void OnproIdChanged();
    #endregion
		
		public tblCompra()
		{
			this._tblProducto = default(EntityRef<tblProducto>);
			this._tblProveedor = default(EntityRef<tblProveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int comId
		{
			get
			{
				return this._comId;
			}
			set
			{
				if ((this._comId != value))
				{
					this.OncomIdChanging(value);
					this.SendPropertyChanging();
					this._comId = value;
					this.SendPropertyChanged("comId");
					this.OncomIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comCodigo", DbType="VarChar(50)")]
		public string comCodigo
		{
			get
			{
				return this._comCodigo;
			}
			set
			{
				if ((this._comCodigo != value))
				{
					this.OncomCodigoChanging(value);
					this.SendPropertyChanging();
					this._comCodigo = value;
					this.SendPropertyChanged("comCodigo");
					this.OncomCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comFechaCompra", DbType="DateTime")]
		public System.Nullable<System.DateTime> comFechaCompra
		{
			get
			{
				return this._comFechaCompra;
			}
			set
			{
				if ((this._comFechaCompra != value))
				{
					this.OncomFechaCompraChanging(value);
					this.SendPropertyChanging();
					this._comFechaCompra = value;
					this.SendPropertyChanged("comFechaCompra");
					this.OncomFechaCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comCantidad", DbType="Int")]
		public System.Nullable<int> comCantidad
		{
			get
			{
				return this._comCantidad;
			}
			set
			{
				if ((this._comCantidad != value))
				{
					this.OncomCantidadChanging(value);
					this.SendPropertyChanging();
					this._comCantidad = value;
					this.SendPropertyChanged("comCantidad");
					this.OncomCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comCapital", DbType="Float")]
		public System.Nullable<double> comCapital
		{
			get
			{
				return this._comCapital;
			}
			set
			{
				if ((this._comCapital != value))
				{
					this.OncomCapitalChanging(value);
					this.SendPropertyChanging();
					this._comCapital = value;
					this.SendPropertyChanged("comCapital");
					this.OncomCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provId", DbType="Int")]
		public System.Nullable<int> provId
		{
			get
			{
				return this._provId;
			}
			set
			{
				if ((this._provId != value))
				{
					if (this._tblProveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnprovIdChanging(value);
					this.SendPropertyChanging();
					this._provId = value;
					this.SendPropertyChanged("provId");
					this.OnprovIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proId", DbType="Int")]
		public System.Nullable<int> proId
		{
			get
			{
				return this._proId;
			}
			set
			{
				if ((this._proId != value))
				{
					if (this._tblProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproIdChanging(value);
					this.SendPropertyChanging();
					this._proId = value;
					this.SendPropertyChanged("proId");
					this.OnproIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProducto_tblCompra", Storage="_tblProducto", ThisKey="proId", OtherKey="proId", IsForeignKey=true)]
		public tblProducto tblProducto
		{
			get
			{
				return this._tblProducto.Entity;
			}
			set
			{
				tblProducto previousValue = this._tblProducto.Entity;
				if (((previousValue != value) 
							|| (this._tblProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblProducto.Entity = null;
						previousValue.tblCompra.Remove(this);
					}
					this._tblProducto.Entity = value;
					if ((value != null))
					{
						value.tblCompra.Add(this);
						this._proId = value.proId;
					}
					else
					{
						this._proId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblProducto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProveedor_tblCompra", Storage="_tblProveedor", ThisKey="provId", OtherKey="provId", IsForeignKey=true)]
		public tblProveedor tblProveedor
		{
			get
			{
				return this._tblProveedor.Entity;
			}
			set
			{
				tblProveedor previousValue = this._tblProveedor.Entity;
				if (((previousValue != value) 
							|| (this._tblProveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblProveedor.Entity = null;
						previousValue.tblCompra.Remove(this);
					}
					this._tblProveedor.Entity = value;
					if ((value != null))
					{
						value.tblCompra.Add(this);
						this._provId = value.provId;
					}
					else
					{
						this._provId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblProveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProducto")]
	public partial class tblProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _proId;
		
		private string _proNombre;
		
		private string _proMarca;
		
		private string _proTalla;
		
		private string _proColor;
		
		private System.Nullable<double> _proPrecio;
		
		private System.Nullable<int> _proCantidad;
		
		private System.Data.Linq.Binary _proArte;
		
		private string _proTituloArte;
		
		private string _proArteNom;
		
		private System.Nullable<char> _proEstado;
		
		private System.Nullable<int> _catId;
		
		private EntitySet<tblVenta> _tblVenta;
		
		private EntitySet<tblCompra> _tblCompra;
		
		private EntityRef<tblCategoria> _tblCategoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproIdChanging(int value);
    partial void OnproIdChanged();
    partial void OnproNombreChanging(string value);
    partial void OnproNombreChanged();
    partial void OnproMarcaChanging(string value);
    partial void OnproMarcaChanged();
    partial void OnproTallaChanging(string value);
    partial void OnproTallaChanged();
    partial void OnproColorChanging(string value);
    partial void OnproColorChanged();
    partial void OnproPrecioChanging(System.Nullable<double> value);
    partial void OnproPrecioChanged();
    partial void OnproCantidadChanging(System.Nullable<int> value);
    partial void OnproCantidadChanged();
    partial void OnproArteChanging(System.Data.Linq.Binary value);
    partial void OnproArteChanged();
    partial void OnproTituloArteChanging(string value);
    partial void OnproTituloArteChanged();
    partial void OnproArteNomChanging(string value);
    partial void OnproArteNomChanged();
    partial void OnproEstadoChanging(System.Nullable<char> value);
    partial void OnproEstadoChanged();
    partial void OncatIdChanging(System.Nullable<int> value);
    partial void OncatIdChanged();
    #endregion
		
		public tblProducto()
		{
			this._tblVenta = new EntitySet<tblVenta>(new Action<tblVenta>(this.attach_tblVenta), new Action<tblVenta>(this.detach_tblVenta));
			this._tblCompra = new EntitySet<tblCompra>(new Action<tblCompra>(this.attach_tblCompra), new Action<tblCompra>(this.detach_tblCompra));
			this._tblCategoria = default(EntityRef<tblCategoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int proId
		{
			get
			{
				return this._proId;
			}
			set
			{
				if ((this._proId != value))
				{
					this.OnproIdChanging(value);
					this.SendPropertyChanging();
					this._proId = value;
					this.SendPropertyChanged("proId");
					this.OnproIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proNombre", DbType="VarChar(75)")]
		public string proNombre
		{
			get
			{
				return this._proNombre;
			}
			set
			{
				if ((this._proNombre != value))
				{
					this.OnproNombreChanging(value);
					this.SendPropertyChanging();
					this._proNombre = value;
					this.SendPropertyChanged("proNombre");
					this.OnproNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proMarca", DbType="VarChar(75)")]
		public string proMarca
		{
			get
			{
				return this._proMarca;
			}
			set
			{
				if ((this._proMarca != value))
				{
					this.OnproMarcaChanging(value);
					this.SendPropertyChanging();
					this._proMarca = value;
					this.SendPropertyChanged("proMarca");
					this.OnproMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proTalla", DbType="VarChar(50)")]
		public string proTalla
		{
			get
			{
				return this._proTalla;
			}
			set
			{
				if ((this._proTalla != value))
				{
					this.OnproTallaChanging(value);
					this.SendPropertyChanging();
					this._proTalla = value;
					this.SendPropertyChanged("proTalla");
					this.OnproTallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proColor", DbType="VarChar(50)")]
		public string proColor
		{
			get
			{
				return this._proColor;
			}
			set
			{
				if ((this._proColor != value))
				{
					this.OnproColorChanging(value);
					this.SendPropertyChanging();
					this._proColor = value;
					this.SendPropertyChanged("proColor");
					this.OnproColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proPrecio", DbType="Float")]
		public System.Nullable<double> proPrecio
		{
			get
			{
				return this._proPrecio;
			}
			set
			{
				if ((this._proPrecio != value))
				{
					this.OnproPrecioChanging(value);
					this.SendPropertyChanging();
					this._proPrecio = value;
					this.SendPropertyChanged("proPrecio");
					this.OnproPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proCantidad", DbType="Int")]
		public System.Nullable<int> proCantidad
		{
			get
			{
				return this._proCantidad;
			}
			set
			{
				if ((this._proCantidad != value))
				{
					this.OnproCantidadChanging(value);
					this.SendPropertyChanging();
					this._proCantidad = value;
					this.SendPropertyChanged("proCantidad");
					this.OnproCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proArte", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary proArte
		{
			get
			{
				return this._proArte;
			}
			set
			{
				if ((this._proArte != value))
				{
					this.OnproArteChanging(value);
					this.SendPropertyChanging();
					this._proArte = value;
					this.SendPropertyChanged("proArte");
					this.OnproArteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proTituloArte", DbType="VarChar(50)")]
		public string proTituloArte
		{
			get
			{
				return this._proTituloArte;
			}
			set
			{
				if ((this._proTituloArte != value))
				{
					this.OnproTituloArteChanging(value);
					this.SendPropertyChanging();
					this._proTituloArte = value;
					this.SendPropertyChanged("proTituloArte");
					this.OnproTituloArteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proArteNom", DbType="VarChar(50)")]
		public string proArteNom
		{
			get
			{
				return this._proArteNom;
			}
			set
			{
				if ((this._proArteNom != value))
				{
					this.OnproArteNomChanging(value);
					this.SendPropertyChanging();
					this._proArteNom = value;
					this.SendPropertyChanged("proArteNom");
					this.OnproArteNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proEstado", DbType="Char(1)")]
		public System.Nullable<char> proEstado
		{
			get
			{
				return this._proEstado;
			}
			set
			{
				if ((this._proEstado != value))
				{
					this.OnproEstadoChanging(value);
					this.SendPropertyChanging();
					this._proEstado = value;
					this.SendPropertyChanged("proEstado");
					this.OnproEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catId", DbType="Int")]
		public System.Nullable<int> catId
		{
			get
			{
				return this._catId;
			}
			set
			{
				if ((this._catId != value))
				{
					if (this._tblCategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncatIdChanging(value);
					this.SendPropertyChanging();
					this._catId = value;
					this.SendPropertyChanged("catId");
					this.OncatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProducto_tblVenta", Storage="_tblVenta", ThisKey="proId", OtherKey="proId")]
		public EntitySet<tblVenta> tblVenta
		{
			get
			{
				return this._tblVenta;
			}
			set
			{
				this._tblVenta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProducto_tblCompra", Storage="_tblCompra", ThisKey="proId", OtherKey="proId")]
		public EntitySet<tblCompra> tblCompra
		{
			get
			{
				return this._tblCompra;
			}
			set
			{
				this._tblCompra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCategoria_tblProducto", Storage="_tblCategoria", ThisKey="catId", OtherKey="catId", IsForeignKey=true)]
		public tblCategoria tblCategoria
		{
			get
			{
				return this._tblCategoria.Entity;
			}
			set
			{
				tblCategoria previousValue = this._tblCategoria.Entity;
				if (((previousValue != value) 
							|| (this._tblCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCategoria.Entity = null;
						previousValue.tblProducto.Remove(this);
					}
					this._tblCategoria.Entity = value;
					if ((value != null))
					{
						value.tblProducto.Add(this);
						this._catId = value.catId;
					}
					else
					{
						this._catId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblCategoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblVenta(tblVenta entity)
		{
			this.SendPropertyChanging();
			entity.tblProducto = this;
		}
		
		private void detach_tblVenta(tblVenta entity)
		{
			this.SendPropertyChanging();
			entity.tblProducto = null;
		}
		
		private void attach_tblCompra(tblCompra entity)
		{
			this.SendPropertyChanging();
			entity.tblProducto = this;
		}
		
		private void detach_tblCompra(tblCompra entity)
		{
			this.SendPropertyChanging();
			entity.tblProducto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProveedor")]
	public partial class tblProveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _provId;
		
		private string _provNombreEmpresa;
		
		private string _provRuc;
		
		private string _provCorresponsal;
		
		private string _provCorreo;
		
		private string _provDireccion;
		
		private System.Nullable<char> _provEstado;
		
		private EntitySet<tblCompra> _tblCompra;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnprovIdChanging(int value);
    partial void OnprovIdChanged();
    partial void OnprovNombreEmpresaChanging(string value);
    partial void OnprovNombreEmpresaChanged();
    partial void OnprovRucChanging(string value);
    partial void OnprovRucChanged();
    partial void OnprovCorresponsalChanging(string value);
    partial void OnprovCorresponsalChanged();
    partial void OnprovCorreoChanging(string value);
    partial void OnprovCorreoChanged();
    partial void OnprovDireccionChanging(string value);
    partial void OnprovDireccionChanged();
    partial void OnprovEstadoChanging(System.Nullable<char> value);
    partial void OnprovEstadoChanged();
    #endregion
		
		public tblProveedor()
		{
			this._tblCompra = new EntitySet<tblCompra>(new Action<tblCompra>(this.attach_tblCompra), new Action<tblCompra>(this.detach_tblCompra));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int provId
		{
			get
			{
				return this._provId;
			}
			set
			{
				if ((this._provId != value))
				{
					this.OnprovIdChanging(value);
					this.SendPropertyChanging();
					this._provId = value;
					this.SendPropertyChanged("provId");
					this.OnprovIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provNombreEmpresa", DbType="VarChar(50)")]
		public string provNombreEmpresa
		{
			get
			{
				return this._provNombreEmpresa;
			}
			set
			{
				if ((this._provNombreEmpresa != value))
				{
					this.OnprovNombreEmpresaChanging(value);
					this.SendPropertyChanging();
					this._provNombreEmpresa = value;
					this.SendPropertyChanged("provNombreEmpresa");
					this.OnprovNombreEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provRuc", DbType="VarChar(50)")]
		public string provRuc
		{
			get
			{
				return this._provRuc;
			}
			set
			{
				if ((this._provRuc != value))
				{
					this.OnprovRucChanging(value);
					this.SendPropertyChanging();
					this._provRuc = value;
					this.SendPropertyChanged("provRuc");
					this.OnprovRucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provCorresponsal", DbType="VarChar(50)")]
		public string provCorresponsal
		{
			get
			{
				return this._provCorresponsal;
			}
			set
			{
				if ((this._provCorresponsal != value))
				{
					this.OnprovCorresponsalChanging(value);
					this.SendPropertyChanging();
					this._provCorresponsal = value;
					this.SendPropertyChanged("provCorresponsal");
					this.OnprovCorresponsalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provCorreo", DbType="VarChar(75)")]
		public string provCorreo
		{
			get
			{
				return this._provCorreo;
			}
			set
			{
				if ((this._provCorreo != value))
				{
					this.OnprovCorreoChanging(value);
					this.SendPropertyChanging();
					this._provCorreo = value;
					this.SendPropertyChanged("provCorreo");
					this.OnprovCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provDireccion", DbType="VarChar(75)")]
		public string provDireccion
		{
			get
			{
				return this._provDireccion;
			}
			set
			{
				if ((this._provDireccion != value))
				{
					this.OnprovDireccionChanging(value);
					this.SendPropertyChanging();
					this._provDireccion = value;
					this.SendPropertyChanged("provDireccion");
					this.OnprovDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provEstado", DbType="Char(1)")]
		public System.Nullable<char> provEstado
		{
			get
			{
				return this._provEstado;
			}
			set
			{
				if ((this._provEstado != value))
				{
					this.OnprovEstadoChanging(value);
					this.SendPropertyChanging();
					this._provEstado = value;
					this.SendPropertyChanged("provEstado");
					this.OnprovEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProveedor_tblCompra", Storage="_tblCompra", ThisKey="provId", OtherKey="provId")]
		public EntitySet<tblCompra> tblCompra
		{
			get
			{
				return this._tblCompra;
			}
			set
			{
				this._tblCompra.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCompra(tblCompra entity)
		{
			this.SendPropertyChanging();
			entity.tblProveedor = this;
		}
		
		private void detach_tblCompra(tblCompra entity)
		{
			this.SendPropertyChanging();
			entity.tblProveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTipoUs")]
	public partial class tblTipoUs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tusuId;
		
		private string _tusuRol;
		
		private EntitySet<tblUsuario> _tblUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntusuIdChanging(int value);
    partial void OntusuIdChanged();
    partial void OntusuRolChanging(string value);
    partial void OntusuRolChanged();
    #endregion
		
		public tblTipoUs()
		{
			this._tblUsuario = new EntitySet<tblUsuario>(new Action<tblUsuario>(this.attach_tblUsuario), new Action<tblUsuario>(this.detach_tblUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusuId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tusuId
		{
			get
			{
				return this._tusuId;
			}
			set
			{
				if ((this._tusuId != value))
				{
					this.OntusuIdChanging(value);
					this.SendPropertyChanging();
					this._tusuId = value;
					this.SendPropertyChanged("tusuId");
					this.OntusuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusuRol", DbType="VarChar(50)")]
		public string tusuRol
		{
			get
			{
				return this._tusuRol;
			}
			set
			{
				if ((this._tusuRol != value))
				{
					this.OntusuRolChanging(value);
					this.SendPropertyChanging();
					this._tusuRol = value;
					this.SendPropertyChanged("tusuRol");
					this.OntusuRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTipoUs_tblUsuario", Storage="_tblUsuario", ThisKey="tusuId", OtherKey="tusuId")]
		public EntitySet<tblUsuario> tblUsuario
		{
			get
			{
				return this._tblUsuario;
			}
			set
			{
				this._tblUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblUsuario(tblUsuario entity)
		{
			this.SendPropertyChanging();
			entity.tblTipoUs = this;
		}
		
		private void detach_tblUsuario(tblUsuario entity)
		{
			this.SendPropertyChanging();
			entity.tblTipoUs = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUsuario")]
	public partial class tblUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usId;
		
		private string _usNombre;
		
		private string _usApellido;
		
		private string _usCorreo;
		
		private string _usLog;
		
		private string _usClave;
		
		private string _usCedula;
		
		private string _usDireccion;
		
		private string _usTelefono;
		
		private System.Nullable<char> _usEstado;
		
		private System.Nullable<int> _tusuId;
		
		private EntityRef<tblTipoUs> _tblTipoUs;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusIdChanging(int value);
    partial void OnusIdChanged();
    partial void OnusNombreChanging(string value);
    partial void OnusNombreChanged();
    partial void OnusApellidoChanging(string value);
    partial void OnusApellidoChanged();
    partial void OnusCorreoChanging(string value);
    partial void OnusCorreoChanged();
    partial void OnusLogChanging(string value);
    partial void OnusLogChanged();
    partial void OnusClaveChanging(string value);
    partial void OnusClaveChanged();
    partial void OnusCedulaChanging(string value);
    partial void OnusCedulaChanged();
    partial void OnusDireccionChanging(string value);
    partial void OnusDireccionChanged();
    partial void OnusTelefonoChanging(string value);
    partial void OnusTelefonoChanged();
    partial void OnusEstadoChanging(System.Nullable<char> value);
    partial void OnusEstadoChanged();
    partial void OntusuIdChanging(System.Nullable<int> value);
    partial void OntusuIdChanged();
    #endregion
		
		public tblUsuario()
		{
			this._tblTipoUs = default(EntityRef<tblTipoUs>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usId
		{
			get
			{
				return this._usId;
			}
			set
			{
				if ((this._usId != value))
				{
					this.OnusIdChanging(value);
					this.SendPropertyChanging();
					this._usId = value;
					this.SendPropertyChanged("usId");
					this.OnusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usNombre", DbType="VarChar(50)")]
		public string usNombre
		{
			get
			{
				return this._usNombre;
			}
			set
			{
				if ((this._usNombre != value))
				{
					this.OnusNombreChanging(value);
					this.SendPropertyChanging();
					this._usNombre = value;
					this.SendPropertyChanged("usNombre");
					this.OnusNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usApellido", DbType="VarChar(50)")]
		public string usApellido
		{
			get
			{
				return this._usApellido;
			}
			set
			{
				if ((this._usApellido != value))
				{
					this.OnusApellidoChanging(value);
					this.SendPropertyChanging();
					this._usApellido = value;
					this.SendPropertyChanged("usApellido");
					this.OnusApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usCorreo", DbType="VarChar(50)")]
		public string usCorreo
		{
			get
			{
				return this._usCorreo;
			}
			set
			{
				if ((this._usCorreo != value))
				{
					this.OnusCorreoChanging(value);
					this.SendPropertyChanging();
					this._usCorreo = value;
					this.SendPropertyChanged("usCorreo");
					this.OnusCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usLog", DbType="VarChar(255)")]
		public string usLog
		{
			get
			{
				return this._usLog;
			}
			set
			{
				if ((this._usLog != value))
				{
					this.OnusLogChanging(value);
					this.SendPropertyChanging();
					this._usLog = value;
					this.SendPropertyChanged("usLog");
					this.OnusLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usClave", DbType="VarChar(50)")]
		public string usClave
		{
			get
			{
				return this._usClave;
			}
			set
			{
				if ((this._usClave != value))
				{
					this.OnusClaveChanging(value);
					this.SendPropertyChanging();
					this._usClave = value;
					this.SendPropertyChanged("usClave");
					this.OnusClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usCedula", DbType="VarChar(10)")]
		public string usCedula
		{
			get
			{
				return this._usCedula;
			}
			set
			{
				if ((this._usCedula != value))
				{
					this.OnusCedulaChanging(value);
					this.SendPropertyChanging();
					this._usCedula = value;
					this.SendPropertyChanged("usCedula");
					this.OnusCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usDireccion", DbType="VarChar(75)")]
		public string usDireccion
		{
			get
			{
				return this._usDireccion;
			}
			set
			{
				if ((this._usDireccion != value))
				{
					this.OnusDireccionChanging(value);
					this.SendPropertyChanging();
					this._usDireccion = value;
					this.SendPropertyChanged("usDireccion");
					this.OnusDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usTelefono", DbType="VarChar(10)")]
		public string usTelefono
		{
			get
			{
				return this._usTelefono;
			}
			set
			{
				if ((this._usTelefono != value))
				{
					this.OnusTelefonoChanging(value);
					this.SendPropertyChanging();
					this._usTelefono = value;
					this.SendPropertyChanged("usTelefono");
					this.OnusTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usEstado", DbType="Char(1)")]
		public System.Nullable<char> usEstado
		{
			get
			{
				return this._usEstado;
			}
			set
			{
				if ((this._usEstado != value))
				{
					this.OnusEstadoChanging(value);
					this.SendPropertyChanging();
					this._usEstado = value;
					this.SendPropertyChanged("usEstado");
					this.OnusEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusuId", DbType="Int")]
		public System.Nullable<int> tusuId
		{
			get
			{
				return this._tusuId;
			}
			set
			{
				if ((this._tusuId != value))
				{
					if (this._tblTipoUs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntusuIdChanging(value);
					this.SendPropertyChanging();
					this._tusuId = value;
					this.SendPropertyChanged("tusuId");
					this.OntusuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTipoUs_tblUsuario", Storage="_tblTipoUs", ThisKey="tusuId", OtherKey="tusuId", IsForeignKey=true)]
		public tblTipoUs tblTipoUs
		{
			get
			{
				return this._tblTipoUs.Entity;
			}
			set
			{
				tblTipoUs previousValue = this._tblTipoUs.Entity;
				if (((previousValue != value) 
							|| (this._tblTipoUs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTipoUs.Entity = null;
						previousValue.tblUsuario.Remove(this);
					}
					this._tblTipoUs.Entity = value;
					if ((value != null))
					{
						value.tblUsuario.Add(this);
						this._tusuId = value.tusuId;
					}
					else
					{
						this._tusuId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblTipoUs");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
